// 进秀电子产品知识库（演示用示例数据）
// 注意：所有价格区间均为虚构示例，仅用于演示选型/报价逻辑，正式部署时替换为真实产品数据。
const PRODUCTS = [
  {
    id: "JX-SB60",
    name: "桌面型隔音箱 JX-SB60",
    category: "声学产品",
    keywords: ["隔音箱", "隔音", "桌面", "小型", "喇叭测试", "音频测试"],
    inner: { l: 600, w: 600, h: 600 },
    noiseReduction: 35,
    desc: "适合桌面音频器件测试：喇叭、蜂鸣器、受话器等小型 DUT。标配观察窗与线缆接口板。",
    priceRange: "¥8,000 – ¥15,000（示例价）",
    leadTime: "2–3 周",
  },
  {
    id: "JX-SB120",
    name: "落地式隔音箱 JX-SB120",
    category: "声学产品",
    keywords: ["隔音箱", "隔音", "落地", "工位", "产线", "中型"],
    inner: { l: 1200, w: 1000, h: 1200 },
    noiseReduction: 40,
    desc: "产线工位级隔音测试箱，适合整机、风机、马达类产品测试。可选排风消音通道与移动脚轮。",
    priceRange: "¥25,000 – ¥45,000（示例价）",
    leadTime: "3–4 周",
  },
  {
    id: "JX-AR",
    name: "静音房（定制）JX-AR 系列",
    category: "声学产品",
    keywords: ["静音房", "静音室", "隔音房", "房间", "实验室"],
    inner: null,
    noiseReduction: 45,
    desc: "步入式静音测试房，按场地尺寸定制，隔音量 30–50dB 可选，适合整机声学实验室。",
    priceRange: "¥80,000 起（示例价，按面积与隔音等级定制）",
    leadTime: "6–8 周（含现场安装）",
  },
  {
    id: "JX-AN",
    name: "消音室（定制）JX-AN 系列",
    category: "声学产品",
    keywords: ["消音室", "消声室", "全消", "半消", "声学测量", "风机", "噪声测试"],
    inner: null,
    noiseReduction: 50,
    desc: "全消/半消音室定制，内壁吸音尖劈结构，本底噪声可达 18dB(A) 以下，用于精密声学测量。",
    priceRange: "¥150,000 起（示例价，按体积与本底噪声指标定制）",
    leadTime: "8–12 周（含现场安装与验收）",
  },
  {
    id: "JX-LR",
    name: "流水线静音室 JX-LR 系列",
    category: "声学产品",
    keywords: ["流水线", "产线", "在线", "静音室", "隧道", "输送"],
    inner: null,
    noiseReduction: 35,
    desc: "嵌入产线的在线静音测试通道，配合输送带开口与软帘设计，不中断节拍完成声学测试。",
    priceRange: "¥60,000 起（示例价，按产线宽度与节拍定制）",
    leadTime: "5–7 周",
  },
  {
    id: "JX-TC-HDMI",
    name: "HDMI 2.1 测试卡",
    category: "线路板 / 测试卡",
    keywords: ["HDMI", "测试卡", "视频", "接口测试", "8K"],
    desc: "支持 HDMI 2.1 协议接口功能测试，48Gbps 带宽，配套上位机软件可输出测试报告。",
    priceRange: "¥1,200 – ¥2,800/张（示例价）",
    leadTime: "现货 / 1 周",
  },
  {
    id: "JX-TC-USBC",
    name: "USB Type-C 全功能测试卡",
    category: "线路板 / 测试卡",
    keywords: ["TYPE-C", "TYPEC", "USB", "测试卡", "PD", "快充", "接口测试"],
    desc: "Type-C 正反插、PD 快充协议、数据传输全功能测试，支持 USB3.2 Gen2。",
    priceRange: "¥900 – ¥2,200/张（示例价）",
    leadTime: "现货 / 1 周",
  },
  {
    id: "JX-TC-LAN",
    name: "千兆网口测试卡",
    category: "线路板 / 测试卡",
    keywords: ["网口", "网卡", "RJ45", "以太网", "测试卡", "千兆"],
    desc: "RJ45 千兆以太网接口测试，支持回环与吞吐量测试模式。",
    priceRange: "¥600 – ¥1,500/张（示例价）",
    leadTime: "现货 / 1 周",
  },
  {
    id: "JX-FX",
    name: "定制工装治具",
    category: "工装治具",
    keywords: ["治具", "工装", "夹具", "定制", "SMT", "过炉", "测试治具", "组装"],
    desc: "按客户图纸/样品定制：SMT 过炉治具、ICT/FCT 测试治具、组装治具等。金属/合成石材质可选。",
    priceRange: "¥800 – ¥20,000/套（示例价，按图纸评估）",
    leadTime: "1–3 周（按复杂度）",
  },
];
